language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t gamemaniaz/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true gamemaniaz/docker-react npm run test -- --coverage